name: chat CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: use node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      # - name: Setup PNPM
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 7.18.1

      # - name: check pnpm
      #   run: pnpm --version

      # 步骤5 部署项目
      # - name: deploy
      #   uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      #   env:
      #     WELCOME: 'ssh scp ssh pipelines'
      #     LASTSSH: 'Doing something after copying'
      #   with:
      #     host: ${{ secrets.HOST }}
      #     user: ${{ secrets.USER }}
      #     pass: ${{ secrets.PASS }}
      #     # port: ${{ secrets.TX_PORT }}
      #     connect_timeout: 20s
      #     first_ssh: |
      #       sudo su
      #       rm -rf /www/wwwroot/chat_nest
      #       mkdir -p /www/wwwroot/chat_nest
      #     scp: |
      #       'chat_nest.zip' => /www/wwwroot/chat_nest
      #     last_ssh: |
      #       cd /www/wwwroot/chat_nest
      #       unzip chat_nest.zip
      #       cd /www/wwwroot/chat_nest
      #       pnpm i
      #       pnpm run start
      #     # pm2 start ./src/main.js
      - name: test
        run: |
          ls /home/runner/work/nest-chat

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rlgoDzvc --delete'
          # SOURCE: './'
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: '/www/wwwroot/chat_nest'
          EXCLUDE: '.gitignore'
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
