name: chat CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          package-manager: pnpm

      - name: install
        run: pnpm install
